<?php
/**
 * Churchville Dental Care — Theme functions.php performance additions
 * Add this code to your child theme's functions.php
 */

if ( ! defined( 'ABSPATH' ) ) exit;

// ─── Google Tag Manager: load after user interaction ──────────────────────────
// Replace GTM-XXXXXX with your actual GTM container ID.
add_action( 'wp_head', function () {
    $gtm_id = 'GTM-XXXXXX';
    ?>
    <script>
    // Delay GTM until first user interaction (saves ~120 KB TBT on mobile)
    (function(){
        var loaded = false;
        function loadGTM(){
            if(loaded) return; loaded = true;
            (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','<?php echo esc_js( $gtm_id ); ?>');
        }
        ['mousedown','touchstart','keydown','scroll'].forEach(function(e){
            window.addEventListener(e, loadGTM, {once:true, passive:true});
        });
        setTimeout(loadGTM, 5000); // hard fallback
    })();
    </script>
    <?php
}, 99 );

// GTM noscript (keep this right after opening <body>)
add_action( 'wp_body_open', function () {
    $gtm_id = 'GTM-XXXXXX';
    echo '<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=' . esc_attr( $gtm_id ) . '"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>';
} );

// ─── Register performance JS with defer ───────────────────────────────────────
add_action( 'wp_enqueue_scripts', function () {
    wp_enqueue_script(
        'cdc-performance',
        get_theme_file_uri( 'js/performance.js' ),
        [],
        '1.0.0',
        [ 'strategy' => 'defer', 'in_footer' => true ]
    );
} );

// ─── Add fetchpriority="high" to hero/LCP image ───────────────────────────────
add_filter( 'wp_get_attachment_image_attributes', function ( $attr, $attachment, $size ) {
    // Tag the first image inserted with [hero] shortcode or specific attachment ID
    static $hero_loaded = false;
    if ( ! $hero_loaded && ( isset( $attr['class'] ) && strpos( $attr['class'], 'hero' ) !== false ) ) {
        $attr['fetchpriority'] = 'high';
        $attr['loading']       = 'eager';
        $hero_loaded = true;
    }
    return $attr;
}, 10, 3 );

// ─── Self-host Google Fonts (eliminates render-blocking external requests) ────
// 1. Run: php scripts/download-fonts.php to download font files locally
// 2. Then uncomment below and remove Google Fonts <link> tags from the theme

/*
add_action( 'wp_enqueue_scripts', function () {
    wp_enqueue_style( 'cdc-fonts', get_theme_file_uri( 'fonts/fonts.css' ), [], null );
}, 1 );
*/

// ─── Responsive images: add WebP sources automatically ───────────────────────
add_filter( 'wp_calculate_image_srcset', function ( $sources ) {
    foreach ( $sources as $width => $source ) {
        $webp_url = preg_replace( '/\.(jpe?g|png)($|\?)/i', '.webp$2', $source['url'] );
        // Only use WebP src if the file was already generated by optimize-images.sh
        // (checking server path would require mapping URL→path, left as runtime check)
    }
    return $sources;
} );

// ─── Remove query strings from static assets (improves proxy cache hit rate) ──
add_filter( 'style_loader_src', 'cdc_remove_query_strings', 10 );
add_filter( 'script_loader_src', 'cdc_remove_query_strings', 10 );
function cdc_remove_query_strings( $src ) {
    // Skip external and admin assets
    if ( strpos( $src, get_site_url() ) === false ) return $src;
    return remove_query_arg( 'ver', $src );
}

// ─── Preload the above-fold font files ───────────────────────────────────────
add_action( 'wp_head', function () {
    $fonts = [
        get_theme_file_uri( 'fonts/open-sans-400.woff2' ),
        get_theme_file_uri( 'fonts/open-sans-700.woff2' ),
    ];
    foreach ( $fonts as $font ) {
        printf(
            '<link rel="preload" as="font" type="font/woff2" href="%s" crossorigin>' . "\n",
            esc_url( $font )
        );
    }
}, 2 );

// ─── Add <meta> viewport (safety check) ──────────────────────────────────────
add_action( 'wp_head', function () {
    if ( ! current_theme_supports( 'title-tag' ) ) return;
    // Ensure viewport meta exists with correct content
    echo '<meta name="viewport" content="width=device-width, initial-scale=1">' . "\n";
}, 1 );
