#!/usr/bin/env php
<?php
/**
 * Churchville Dental Care — Self-host Google Fonts
 * Downloads Google Fonts as WOFF2 and generates a local @font-face CSS file.
 * Run from project root: php scripts/download-fonts.php
 *
 * Why self-host? Eliminates the external fonts.googleapis.com DNS/TCP/TLS
 * round-trip and removes the render-blocking third-party request (saves ~300 ms on mobile).
 */

$FONTS_DIR = __DIR__ . '/../fonts';
$CSS_FILE  = $FONTS_DIR . '/fonts.css';

// Define the fonts used on the site — adjust to match your Google Fonts URL
$FONTS = [
    [
        'family'  => 'Open Sans',
        'slug'    => 'open-sans',
        'weights' => [ '400', '400italic', '600', '700' ],
    ],
    // Add more font families here if needed, e.g.:
    // [ 'family' => 'Roboto', 'slug' => 'roboto', 'weights' => ['400','700'] ],
];

if ( ! is_dir( $FONTS_DIR ) ) {
    mkdir( $FONTS_DIR, 0755, true );
}

$css_output = "/* Self-hosted Google Fonts — generated by download-fonts.php */\n";

foreach ( $FONTS as $font ) {
    foreach ( $font['weights'] as $weight_str ) {
        $is_italic = strpos( $weight_str, 'italic' ) !== false;
        $weight    = (int) $weight_str;
        $style     = $is_italic ? 'italic' : 'normal';

        // Build Google Fonts API URL for WOFF2
        $api_url = sprintf(
            'https://fonts.googleapis.com/css2?family=%s:ital,wght@%d,%d&display=swap',
            urlencode( $font['family'] ),
            $is_italic ? 1 : 0,
            $weight
        );

        // Fetch the CSS (requesting with a modern UA gets WOFF2)
        $opts = [
            'http' => [
                'header' => "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36\r\n",
            ],
        ];
        $ctx      = stream_context_create( $opts );
        $font_css = @file_get_contents( $api_url, false, $ctx );

        if ( ! $font_css ) {
            echo "WARN: Could not fetch CSS for {$font['family']} {$weight} {$style}\n";
            continue;
        }

        // Extract WOFF2 URLs from the CSS
        preg_match_all( '/src: url\(([^)]+\.woff2)\)/', $font_css, $matches );

        foreach ( $matches[1] as $woff2_url ) {
            $filename = $font['slug'] . '-' . $weight . ( $is_italic ? '-italic' : '' ) . '.woff2';
            $dest     = $FONTS_DIR . '/' . $filename;

            if ( file_exists( $dest ) ) {
                echo "EXISTS: $filename\n";
            } else {
                $data = @file_get_contents( $woff2_url, false, $ctx );
                if ( $data ) {
                    file_put_contents( $dest, $data );
                    echo "DOWNLOADED: $filename (" . round( strlen( $data ) / 1024, 1 ) . " KB)\n";
                } else {
                    echo "FAILED: $filename from $woff2_url\n";
                }
            }

            // Build @font-face rule
            $css_output .= <<<CSS

@font-face {
  font-family: '{$font['family']}';
  font-style: {$style};
  font-weight: {$weight};
  font-display: swap;
  src: url('../fonts/{$filename}') format('woff2');
}
CSS;
            break; // only need the first (subset) URL per weight
        }
    }
}

file_put_contents( $CSS_FILE, $css_output );
echo "\nWrote: $CSS_FILE\n";
echo "Done. Now enqueue 'fonts/fonts.css' from your theme instead of Google Fonts.\n";
